repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3
<<<<<<< HEAD
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
=======
>>>>>>> fd4b54d (Refactor CLIP recipe module and add fine-tuner)
