# Default training configuration for ai4kitchen.
trainer:
  max_epochs: 5
  accelerator: auto
  devices: auto
model:
  encoder: clip
  decoder: transformer
  learning_rate: 1.0e-4
data:
  dataset_name: kaggle_food_recipes
  train_split: train[:90%]
  val_split: train[-10%:]
  cache_dir: null
