name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]
      - name: Run pre-commit checks
        run: pre-commit run --all-files
      - name: Run static type checks
        run: mypy src
      - name: Run tests
        run: pytest
      - name: Run CLIP mini-training smoke test
        run: bash scripts/run_mini_training.sh --epochs 3 --dataset-size 8 --batch-size 4
